### ISSUE TITLE
Build warnings that leads to a failure in loading 

### ISSUE THREAD

**Issue by pkchit** [KxSystems/hdf5#21]
"'/home/puneet/q/l64/libkdbhdf5.so: undefined symbol: inflate
  [3]  /home/puneet/q/hdf5.q:62: .hdf5,:(`$4_'string funcs[;0])!LIBPATH@/:funcs"
this error si displayed and the build warning refers to the file hdf5_ls.c with the following lines:
H5Oget_info1(file,&infobuf);
and 
  H5Oget_info_by_name1(loc_id, name, &infobuf, H5P_DEFAULT);

**Comment by cmccarthy1** [comment]
Hi @pkchit 

What version of the HDF5 C api are you using?

Per the README.md file the interface is supported for the `HDF5 C api >=1.10.4` https://github.com/KxSystems/hdf5#requirements

We have noticed this error previously with versions `<1.10.4` namely with `1.10.1` on Linux

All the best,

Conor

**Comment by pkchit** [comment]
Hey conor,
i moved to verson 1.12.0 and it still gives me this error while installing
/home/puneet/hdf5-master/src/hdf5_read.c: In function ‘readDataCompound’:
/home/puneet/hdf5-master/src/hdf5_read.c:170:3: warning: ‘mtype’ may be
used uninitialized in this function [-Wmaybe-uninitialized]
  170 |   H5Tclose(mtype);
      |   ^~~~~~~~~~~~~~~
and this error while running:
'libhdf5.so.200: cannot open shared object file: No such file or directory
  [3]  /home/puneet/q/hdf5.q:62: .hdf5,:(`$4_'string funcs[;0])!LIBPATH@
/:funcs

It would be great if you could help.

Regards,
Puneet

**Comment by cmccarthy1** [comment]
It appears that you can't find the libhdf5.so shared object from the HDF5 C API.

Have you added the location of your C API install to your LD_LIBRARY_PATH/DYLD_LIBRARY_PATH following the instructions [here](https://github.com/KxSystems/hdf5#third-party-library-installation)?

**Comment by pkchit** [comment]
Thanks for assistance, its working now. I installed another version of the
release and it worked fine.

**Comment by cmccarthy1** [comment]
No problem. Closing this issue now, if you have any other issues please open another issue.
