### ISSUE TITLE
The interface works till the termial is open

### ISSUE THREAD

**Issue by pkchit** [KxSystems/hdf5#22]
After you restart the terminal it stops working and i have to build it again. I dont understand what the issue is, building it again everytime is annoying. i m using kdb 4.0 and hdf5 1.12.0

**Comment by cmccarthy1** [comment]
Hi @pkchit 

It sounds like the interface isn't able to find the `libhdf5.so` shared object from the HDF5 group at run time.

As outlined in the `README.md` [here](https://github.com/KxSystems/hdf5/blob/master/README.md#third-party-library-installation) have you added the location of the `lib` folder of the HDF5 C API to your `LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH`?

This gives the interface a location where it may be able to find the required HDF5 group shared object at run time, which the interface needs. If you are doing the export on a per session basis then you may want to consider making it permanent by adding to your `~/.bashrc`. Doing this is outlined in the accepted answer [here](https://stackoverflow.com/questions/13046624/how-to-permanently-export-a-variable-in-linux).

All the best,

Conor

**Comment by pkchit** [comment]
Thanks for the quick response. It works fine now

Regards,
Puneet

**Comment by cmccarthy1** [comment]
No problem at all
