### ISSUE TITLE
Unable to read Json strings

### ISSUE THREAD

**Issue by pkchit** [KxSystems/hdf5#25]
The function .hdf5.readDataset return an empty table while trying to read a Dataset with a json string stored in a cell. Is there a way to read it?

**Comment by cmccarthy1** [comment]
Hi @pkchit 

Can you provide a minimal example to reproduce? If it requires us to reproduce the dataset external to q can you also provide the method to generate this dataset.

We're currently supporting the vast majority of reasonable base level C type conversions between HDF5 and q handled by the HDF5 C api so some functionality may be missing at the moment.

If this can't be done at the time being we'll add it to development pipeline for a future release.

All the best,

Conor

**Comment by pkchit** [comment]
Hey conor,
Actually the HDF5 file already exists so idk how it was created, but when
you read it in python it returns a string with a prefix b. Example:
b'[\n "Hello world",\n "Words",....]\n'

**Comment by cmccarthy1** [comment]
Ok that's a byte represented string, I'll take a look into that and see if I can replicate it. If there's a quick fix I'll for the issue I'll add it into the interface prior to full release of 1.0.0, (currently on a release candidate). Otherwise I'll add it to the dev timeline for the interface and update here as appropriate

**Comment by pkchit** [comment]
Thanks that would be a great help, please let me know as soon as you can.

**Comment by pkchit** [comment]
Hey,
Can you provide me with some documentation on how the API works internally
for the readDataset function. I was having some difficulty following the
code.

Thanks,
Puneet

**Comment by cmccarthy1** [comment]
Apologies for the delay in response previously we had been attempting to replicate the issue by creating a python equivalent but at present haven't been able to do so.

That's quiet an involved function, are there particular aspect of it that you're having difficulty understanding and I can try to summarise?

The function essentially has two branches one which handles compound HDF5 data (tables) and the other which handles homogenous arrays of data of N dimensions. Each of these has different logic for handling strings vs numeric values and logic to handle conversions from the HDF5 data to equivalent q types.

**Comment by pkchit** [comment]
Yea i am particularly interested in how it reads compound data and
translates into equivalent q. I cant get a hold of the K object in the
functions.

**Comment by pkchit** [comment]
Hey,
I am attaching some strange findings from my side. When i create a
string dataset using python it only reads the last value. I am attaching
screenshots for the same. In q ignore the print statements, I added them to
monitor flow.
I tried this multiple times and it always return only the last value.

**Comment by cmccarthy1** [comment]
Hi,

Your attachment doesn't get included in the email sent I don't believe, could you please provide the code snippets in a way that we can reproduce.

All the best,

Conor

**Comment by pkchit** [comment]
import h5py
hf = h5py.File('data_test3.h5', 'w')
S = [b'[\n "sfdk",\n "fefsf",\n "fdsfsdf"]\n',b'fdsd']

hf.create_dataset('dataset_1',data=S)


q).hdf5.readDataset[fname;"dataset_1"]
"fdsd"

**Comment by cmccarthy1** [comment]
Thanks for the additional information we'll take a look into this.

**Comment by pkchit** [comment]
Sure, do let me know if this can be worked out and kindly share the
documentation as discussed before on reading compound dataset strings.

**Comment by cmccarthy1** [comment]
The behaviour in the example you provided was a bug. Indexing for fixed length strings was starting at index 1 not 0 hence was skipping the first element. That'll be fixed the start of next week.

If you could please provide specific questions around the working of the compound string data function that would speed up the process.

**Comment by cmccarthy1** [comment]
I've drafted a new release of the interface to fix the issue raised above relating to indexing starting at 1 rather than 0, could you please check to see if this modification rectifies your original issue.

**Comment by pkchit** [comment]
Yes i had modified it locally and checked. It works just fine now. Thanks
for your help.
